#!/bin/bash
mpirun -np 4 ./runaway -fk_type "slab" -fdjac -atol 1e-14 -rtol 1e-14 -stol 1e-14 -snes_max_it 100 -snes_max_funcs 200000 -maxit 0 -snes_type newtonls -snes_linesearch_type l2 -snes_mf_operator -snes_max_linear_solve_fail 1000 -ksp_type gmres -ksp_gmres_restart 150 -ksprtol 2e-16 -kspatol 2e-16 -ksp_max_it 1000 -ksp_monitor_true_residual
