#!/bin/bash
mpirun -np 8 ./runaway -fk_type "slab" -fdjac -atol 1e-15 -rtol 1e-15 -stol 1e-15 -snes_max_it 100 -snes_max_funcs 20000 -maxit 0 -snes_type newtonls -snes_linesearch_type l2 -pc_type lu -pc_factor_mat_solver_type superlu_dist -ksp_type preonly -mat_superlu_dist_iterrefine -snes_monitor
